@props(['catalog' => null, 'sizes'])

@php($editing = $catalog !== null)

<div class="grid gap-6">
    <div><label class="text-sm font-semibold" for="title">Judul produk Laverie</label><input class="mt-2 w-full rounded-2xl border border-stone-200 bg-white px-4 py-3 outline-none focus:border-stone-500 focus:ring-4 focus:ring-stone-200" id="title" name="title" value="{{ old('title', $catalog?->title) }}" required maxlength="150"><x-input-error :messages="$errors->get('title')" /></div>
    <div><label class="text-sm font-semibold" for="description">Deskripsi</label><textarea class="mt-2 min-h-36 w-full rounded-2xl border border-stone-200 bg-white px-4 py-3 outline-none focus:border-stone-500 focus:ring-4 focus:ring-stone-200" id="description" name="description" required maxlength="5000">{{ old('description', $catalog?->description) }}</textarea><x-input-error :messages="$errors->get('description')" /></div>
    <div class="grid gap-5 sm:grid-cols-2"><div><label class="text-sm font-semibold" for="price">Harga (Rp)</label><input class="mt-2 w-full rounded-2xl border border-stone-200 bg-white px-4 py-3 outline-none focus:border-stone-500 focus:ring-4 focus:ring-stone-200" id="price" name="price" type="number" min="1" max="99999999.99" step="0.01" value="{{ old('price', $catalog?->price) }}" required><x-input-error :messages="$errors->get('price')" /></div><div><label class="text-sm font-semibold" for="size">Ukuran</label><select class="mt-2 w-full rounded-2xl border border-stone-200 bg-white px-4 py-3 outline-none focus:border-stone-500 focus:ring-4 focus:ring-stone-200" id="size" name="size" required>@foreach ($sizes as $size)<option value="{{ $size->value }}" @selected(old('size', $catalog?->size?->value) === $size->value)>{{ $size->value }}</option>@endforeach</select><x-input-error :messages="$errors->get('size')" /></div></div>
    <div><label class="text-sm font-semibold" for="images">{{ $editing ? 'Ganti gambar (opsional)' : 'Gambar produk' }}</label><input class="mt-2 block w-full rounded-2xl border border-dashed border-stone-300 bg-stone-100 px-4 py-6 text-sm" id="images" name="images[]" type="file" accept="image/jpeg,image/png,image/webp" multiple @required(! $editing)><p class="mt-2 text-xs text-stone-500">Maksimal 5 gambar, masing-masing 4 MB. JPG, PNG, atau WebP.</p><x-input-error :messages="$errors->get('images')" /><x-input-error :messages="$errors->get('images.*')" /></div>
    <label class="flex items-center gap-3"><input class="size-5 rounded border-stone-300 text-stone-900 focus:ring-stone-300" name="is_active" type="checkbox" value="1" @checked(old('is_active', $catalog?->is_active ?? true))><span class="text-sm font-semibold">Tampilkan produk di toko publik</span></label>
</div>