@props(['product' => null, 'categories'])

@php($editing = $product !== null)

<div class="grid gap-6">
    <fieldset><legend class="text-sm font-semibold">Ukuran tersedia di Shop All</legend><p class="mt-1 text-xs text-stone-500">Pilih semua ukuran yang dapat menggunakan produk ini.</p><div class="mt-3 grid grid-cols-4 gap-3">@foreach (['XS', 'S', 'M', 'L'] as $size)<label class="flex items-center gap-2 rounded-xl border border-stone-200 px-3 py-3 text-sm font-semibold"><input class="size-4" name="available_sizes[]" type="checkbox" value="{{ $size }}" @checked(in_array($size, old('available_sizes', $product?->available_sizes ?? []), true))>{{ $size }}</label>@endforeach</div><x-input-error :messages="$errors->get('available_sizes')" /><x-input-error :messages="$errors->get('available_sizes.*')" /></fieldset>
    <div><label class="text-sm font-semibold" for="name">Nama produk</label><input class="mt-2 w-full rounded-2xl border border-stone-200 bg-white px-4 py-3" id="name" name="name" value="{{ old('name', $product?->name) }}" required maxlength="150"><x-input-error :messages="$errors->get('name')" /><x-input-error :messages="$errors->get('slug')" /></div>
    <div><label class="text-sm font-semibold" for="category_id">Kategori</label><select class="mt-2 w-full rounded-2xl border border-stone-200 bg-white px-4 py-3" id="category_id" name="category_id" required><option value="">Pilih kategori</option>@foreach ($categories as $category)<option value="{{ $category->id }}" @selected((int) old('category_id', $product?->category_id) === $category->id)>{{ $category->name }}</option>@endforeach</select><x-input-error :messages="$errors->get('category_id')" /></div>
    <div><label class="text-sm font-semibold" for="description">Deskripsi</label><textarea class="mt-2 min-h-36 w-full rounded-2xl border border-stone-200 bg-white px-4 py-3" id="description" name="description" required maxlength="5000">{{ old('description', $product?->description) }}</textarea><x-input-error :messages="$errors->get('description')" /></div>
    <div class="grid gap-5 sm:grid-cols-2"><div><label class="text-sm font-semibold" for="price">Harga (Rp)</label><input class="mt-2 w-full rounded-2xl border border-stone-200 bg-white px-4 py-3" id="price" name="price" type="number" min="0" max="99999999.99" step="0.01" value="{{ old('price', $product?->price) }}" required><x-input-error :messages="$errors->get('price')" /></div><div><label class="text-sm font-semibold" for="stock">Stok</label><input class="mt-2 w-full rounded-2xl border border-stone-200 bg-white px-4 py-3" id="stock" name="stock" type="number" min="0" max="1000000" step="1" value="{{ old('stock', $product?->stock ?? 0) }}" required><x-input-error :messages="$errors->get('stock')" /></div></div>

    @if ($editing && $product->images->isNotEmpty())
        <fieldset><legend class="text-sm font-semibold">Gambar saat ini & primary image</legend><div class="mt-3 grid gap-4 sm:grid-cols-2">@foreach ($product->images as $image)<div class="rounded-2xl border border-stone-200 p-3"><img class="aspect-[4/3] w-full rounded-xl bg-stone-100 object-cover" src="{{ Storage::disk('public')->url($image->image_path) }}" alt="{{ $product->name }} image {{ $loop->iteration }}"><label class="mt-3 flex items-center gap-2 text-sm font-semibold"><input name="primary_image_id" type="radio" value="{{ $image->id }}" @checked((int) old('primary_image_id', $product->primaryImage?->id) === $image->id)> Primary</label><button class="mt-3 text-sm font-semibold text-stone-600" type="submit" form="delete-product-image-{{ $image->id }}">Hapus gambar</button></div>@endforeach</div><x-input-error :messages="$errors->get('primary_image_id')" /></fieldset>
    @endif

    <div><label class="text-sm font-semibold" for="images">{{ $editing ? 'Tambah gambar (opsional)' : 'Gambar produk (opsional)' }}</label><input class="mt-2 block w-full rounded-2xl border border-dashed border-stone-300 bg-stone-100 px-4 py-6 text-sm" id="images" name="images[]" type="file" accept="image/jpeg,image/png,image/webp" multiple><p class="mt-2 text-xs text-stone-500">Maksimal 8 gambar per upload, masing-masing 5 MB.</p><x-input-error :messages="$errors->get('images')" /><x-input-error :messages="$errors->get('images.*')" /></div>
    <div><label class="text-sm font-semibold" for="new_primary_image_index">Primary dari upload baru (opsional)</label><input class="mt-2 w-full rounded-2xl border border-stone-200 bg-white px-4 py-3" id="new_primary_image_index" name="new_primary_image_index" type="number" min="0" max="7" step="1" value="{{ old('new_primary_image_index') }}"><p class="mt-2 text-xs text-stone-500">Gunakan 0 untuk gambar pertama, 1 untuk gambar kedua, dan seterusnya. Jika kosong dan belum ada gambar primary, gambar pertama dipilih otomatis.</p><x-input-error :messages="$errors->get('new_primary_image_index')" /></div>
    <label class="flex items-center gap-3"><input class="size-5 rounded border-stone-300 text-stone-900" name="is_active" type="checkbox" value="1" @checked(old('is_active', $product?->is_active ?? true))><span class="text-sm font-semibold">Tampilkan produk di storefront</span></label>
</div>